/*
 * Service for namespace yadayada
 *
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing BatchRequestsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BatchRequestsApiTests : IDisposable
    {
        private BatchRequestsApi instance;

        public BatchRequestsApiTests()
        {
            instance = new BatchRequestsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchRequestsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BatchRequestsApi
            //Assert.IsType<BatchRequestsApi>(instance);
        }

        /// <summary>
        /// Test BatchPost
        /// </summary>
        [Fact]
        public void BatchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BatchPost();
            //Assert.IsType<string>(response);
        }
    }
}
