# https://openapi-generator.tech/docs/generators/csharp-netcore/
targetFramework: net6.0
library: httpclient
nullableReferenceTypes: true
disallowAdditionalPropertiesIfNotPresent: false
modelPropertyNaming: original
netCoreProjectFile: true