/*
 * Service for namespace yadayada
 *
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorErrorMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorErrorMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorErrorMessage
        //private ErrorErrorMessage instance;

        public ErrorErrorMessageTests()
        {
            // TODO uncomment below to create an instance of ErrorErrorMessage
            //instance = new ErrorErrorMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorErrorMessage
        /// </summary>
        [Fact]
        public void ErrorErrorMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorErrorMessage
            //Assert.IsType<ErrorErrorMessage>(instance);
        }


        /// <summary>
        /// Test the property 'lang'
        /// </summary>
        [Fact]
        public void langTest()
        {
            // TODO unit test for the property 'lang'
        }
        /// <summary>
        /// Test the property 'value'
        /// </summary>
        [Fact]
        public void valueTest()
        {
            // TODO unit test for the property 'value'
        }

    }

}
