/*
 * Service for namespace yadayada
 *
 * This service is located at [https://localhost/service-root/](https://localhost/service-root/)
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorError
        //private ErrorError instance;

        public ErrorErrorTests()
        {
            // TODO uncomment below to create an instance of ErrorError
            //instance = new ErrorError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorError
        /// </summary>
        [Fact]
        public void ErrorErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorError
            //Assert.IsType<ErrorError>(instance);
        }


        /// <summary>
        /// Test the property 'code'
        /// </summary>
        [Fact]
        public void codeTest()
        {
            // TODO unit test for the property 'code'
        }
        /// <summary>
        /// Test the property 'message'
        /// </summary>
        [Fact]
        public void messageTest()
        {
            // TODO unit test for the property 'message'
        }
        /// <summary>
        /// Test the property 'innererror'
        /// </summary>
        [Fact]
        public void innererrorTest()
        {
            // TODO unit test for the property 'innererror'
        }

    }

}
